version: '2'

services:
  openbox:
    image: jseguillon/openbox:alpine
    container_name: openbox
    volumes:
      - ./source/:/usr/share/source
    networks:
      - os
    stdin_open: true
    tty: true

networks:
  os:
    driver: bridge
